import type { BundleListing, PendingBundle, LinkWarning } from './types.js';

export function findUniqueName(baseName: string, usedNames: Set<string>): string {
  let n = 2;
  let candidate = `${baseName} ${n}`;
  while (usedNames.has(candidate)) {
    n++;
    candidate = `${baseName} ${n}`;
  }
  return candidate;
}

export function resolveBundleNames(
  pendingBundles: PendingBundle[],
): { listings: Map<PendingBundle, BundleListing>; warnings: LinkWarning[] } {
  const warnings: LinkWarning[] = [];

  // Step 1: Sort by full link ID for deterministic ordering
  const sorted = [...pendingBundles].sort((a, b) =>
    a.linkId.localeCompare(b.linkId)
  );

  // Step 2: Assign initial names
  type Entry = { pending: PendingBundle; name: string };
  const entries: Entry[] = sorted.map((pending) => ({
    pending,
    name: pending.config?.title ?? `Bundle ${pending.suffix}`,
  }));

  // Step 3: Group by name to find duplicates
  const nameGroups = new Map<string, Entry[]>();
  for (const entry of entries) {
    const group = nameGroups.get(entry.name) ?? [];
    group.push(entry);
    nameGroups.set(entry.name, group);
  }

  // Track all final assigned names for uniqueness
  const assignedNames = new Set<string>();
  for (const [name, group] of nameGroups) {
    if (group.length === 1) {
      assignedNames.add(name);
    }
  }

  // Step 4: Disambiguate each collision group
  for (const [baseName, group] of nameGroups) {
    if (group.length <= 1) continue;

    const userDefined = group.filter((e) => e.pending.config?.title);
    const autoGenerated = group.filter((e) => !e.pending.config?.title);

    // Pass 1: User-defined titles — first keeps bare, rest get numbered
    if (userDefined.length > 0) {
      assignedNames.add(baseName);
      for (let i = 1; i < userDefined.length; i++) {
        const newName = findUniqueName(baseName, assignedNames);
        userDefined[i]!.name = newName;
        assignedNames.add(newName);

        warnings.push({
          linkUrl: userDefined[i]!.pending.paymentLink,
          reason: `duplicate bundle title "${baseName}" — disambiguated to "${newName}"`,
        });
      }
    }

    // Pass 2: Auto-generated — check against all assigned names
    let firstAutoKeptBare = false;
    for (const entry of autoGenerated) {
      if (!firstAutoKeptBare && !assignedNames.has(baseName)) {
        assignedNames.add(baseName);
        firstAutoKeptBare = true;
      } else {
        const newName = findUniqueName(baseName, assignedNames);
        entry.name = newName;
        assignedNames.add(newName);

        if (userDefined.length > 0) {
          warnings.push({
            linkUrl: entry.pending.paymentLink,
            reason: `auto-generated name "${baseName}" collides with configured title — disambiguated to "${newName}"`,
          });
        } else {
          warnings.push({
            linkUrl: entry.pending.paymentLink,
            reason: `display name collision — disambiguated to "${newName}"`,
          });
        }
      }
    }
  }

  const listings = new Map<PendingBundle, BundleListing>();
  for (const entry of entries) {
    listings.set(entry.pending, {
      kind: 'bundle' as const,
      name: entry.name,
      description: entry.pending.description,
      image: entry.pending.image,
      imageAlt: entry.pending.imageAlt,
      price: entry.pending.price,
      rawPrice: entry.pending.rawPrice,
      currency: entry.pending.currency,
      paymentLink: entry.pending.paymentLink,
    });
  }

  return { listings, warnings };
}
